#!/usr/bin/env tm-env-bash
#
# For testing performance. Run with 'time'

#source "$TM_HOME/.bashrc_script"
echo "scaratch"
_tm::source::include ../bin/.tm.script.sh ../bin/.tm.plugin.sh ../bin/.tm.plugins.sh @tm/lib.file.ini.sh

env | grep TM

SCRATCH_HOME="$(cd "$(dirname "${BASH_SOURCE[0]}" )" && pwd)"


# _tm::plugins::find_ini_files

# declare -a files
# _tm::plugins::__plugin_files_to_array files

# echo "array files: ${files[@]}"

# for file in "${files[@]}"; do
#     echo "file:$file"
# done

_callback(){
    local -n plugin="$1"

    echo "plugin=${plugin[@]}"
}


_tm::plugins::foreach_available_callback _callback